### ISSUE TITLE
Reown fails in iOS if connected network is not Sepolia and tries to switch

### ISSUE THREAD

**Issue by juans-chainsafe** [ChainSafe/web3.unity#1264]
**Describe the bug**
If the network that you have in Metamask is not Sepolia, and you connect with Reown, it will try to switch to Sepolia but it fails

**Steps**
1. Build in iOS
2. Connect with Reown
3. Connect with Metamask
4. Sign message in Metamask
5. Go back to Unity app
6. It will switch you back to Metamask
7. Nothing happens in Metamask
8. Go back to Unity app

**Expected behavior**
Network is switched to Sepolia

**Console errors**
```
Web3Exception: HTTP.POST to ‘https://rpc.walletconnect.com/v1?chainId=eip155:8333&projectId=f4bff60eb260841f46b1c77588cd8acb’ responded with error: {“status”:“FAILED”,“reasons”:[{“field”:“chainId”,“description”:“We don’t support the chainId you provided: eip155:8333. See the list of supported chains here: https://docs.walletconnect.com/cloud/blockchain-api#supported-chains”}]}
 at ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient.UnityWebRequestToNetworkResponse (UnityEngine.Networking.UnityWebRequest request) [0x00000] in <00000000000000000000000000000000>:0
 at ChainSafe.Gaming.Web3.Core.Unity.UnityHttpClient+<>c__DisplayClass3_0.<PostRaw>b__0 () [0x00000] in <00000000000000000000000000000000>:0
 at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0
 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run () [0x00000] in <00000000000000000000000000000000>:0
 at IEnumeratorAwaitExtensions+InstructionWrappers+<ReturnSelf>d__2`1[T].MoveNext () [0x00000] in <00000000000000000000000000000000>:0
 at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
--- End of stack trace from previous location where exception was thrown ---
**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
```

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [iOS]
 - Device Type: [Real device]
 - OS Version: [latest]

**Comment by kantagara** [comment]
This one is on the reown team. I'll update the dependency to their latest .NET version. it's stated that everything is fixed there.

**Comment by juans-chainsafe** [comment]
The initial error doesn't appear anymore, but we still have the issue present with the same reproducible steps.
Now, sometimes, switches the network in Metamask, but the message "Switching the network to: Sepolia..." doesn't disappear in our app, making the user close the app and open it again.

![Image](https://github.com/user-attachments/assets/1add0a3e-0aa8-4ab2-afb4-88d9109af57e)

cc @kantagara
